FROM node:18-alpine

WORKDIR /app

ARG VITE_POSTS_SERVICE_URL
ARG VITE_USERS_SERVICE_URL
ARG VITE_COMMENTS_SERVICE_URL
ARG VITE_LIKES_SERVICE_URL
ARG VITE_PROFILE_SERVICE_URL
ARG VITE_SERVERLESS_FUNCTION_URL

ENV VITE_POSTS_SERVICE_URL=$VITE_POSTS_SERVICE_URL
ENV VITE_USERS_SERVICE_URL=$VITE_USERS_SERVICE_URL
ENV VITE_COMMENTS_SERVICE_URL=$VITE_COMMENTS_SERVICE_URL
ENV VITE_LIKES_SERVICE_URL=$VITE_LIKES_SERVICE_URL
ENV VITE_PROFILE_SERVICE_URL=$VITE_PROFILE_SERVICE_URL
ENV VITE_SERVERLESS_FUNCTION_URL=$VITE_SERVERLESS_FUNCTION_URL

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
